### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by mkorshe** [quadbiolab/VoxHunt#1]
Hello! 

I cannot install VoxHunt. Can you please help me?

ERROR: lazy loading failed for package ‘voxhunt’
* removing ‘/home/mkorshe/R/x86_64-redhat-linux-gnu-library/3.3/voxhunt’
Error: Failed to install 'voxhunt' from GitHub:
  (converted from warning) installation of package ‘/tmp/Rtmps5oM4J/file254024db3c697/voxhunt_0.5.1.tar.gz’ had non-zero exit status

**Comment by joschif** [comment]
Hello mkorshe,

thank you for reporting the problem. It would be great if you could provide me with your input command and the full error message. It is possible that some dependencies were not properly installed (loomR?). I updated the README accordingly.

Best,
Jonas

**Comment by mkorshe** [comment]
Probably, it was a problem with RStudio. 
Because when I tried to install it in a terminal. I redownloaded  'hhoeflin/hdf5r' (at I suppose, that was the second main problem) and it started working.

Thank you!
