### ISSUE TITLE
Installation problem (Lazy loading failed for 'package' voxhunt)

### ISSUE THREAD

**Issue by fkrbry** [quadbiolab/VoxHunt#3]
Hi,

Having bit of a problem installing voxhunt (Rstudio v1.2.5033, OsX). Here is the error below. Solution offered in issue #1 (reinstalling 'hhoeflin/hdf5r') did not help in this case. Would appreciate any help! 

> devtools::install_github('immunogenomics/presto')
Skipping install of 'presto' from a github remote, the SHA1 (7f63f960) has not changed since last install.
  Use `force = TRUE` to force installation
> devtools::install_github('quadbiolab/voxhunt')
Downloading GitHub repo quadbiolab/voxhunt@master
✓  checking for file ‘/private/var/folders/5n/wwyb571x5mz5ktkl0qyt4lwc0000gn/T/Rtmp8zNpfK/remotesd5684a9cd2d6/quadbiolab-VoxHunt-be3ee72/DESCRIPTION’ ...
─  preparing ‘voxhunt’:
✓  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘voxhunt_0.6.0.tar.gz’ (5.1s)
   
* installing *source* package ‘voxhunt’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
Error: (converted from warning) package ‘tibble’ was built under R version 3.6.2
Execution halted
ERROR: lazy loading failed for package ‘voxhunt’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/voxhunt’
Error: Failed to install 'voxhunt' from GitHub:
  (converted from warning) installation of package ‘/var/folders/5n/wwyb571x5mz5ktkl0qyt4lwc0000gn/T//Rtmp8zNpfK/filed5687dd605de/voxhunt_0.6.0.tar.gz’ had non-zero exit status

**Comment by joschif** [comment]
Hi fkrbry,

thanks for reporting the problem. It seems like your issue is related to your `tibble` installation and/or you version of R. If your R version is not the most recent, maybe try updating it and reinstalling `tibble`. If that does not help, please provide me with the output of `sessionInfo()`.

Best,
Jonas

**Comment by fkrbry** [comment]
Reinstalling tibble didn't help unfortunately, still getting the same error. Here is the session info:

> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] rstudioapi_0.11   magrittr_1.5      usethis_1.6.0     devtools_2.3.0    pkgload_1.0.2     R6_2.4.1         
 [7] rlang_0.4.5       fansi_0.4.1       tools_3.6.1       pkgbuild_1.0.6    sessioninfo_1.1.1 cli_2.0.2        
[13] withr_2.1.2       ellipsis_0.3.0    remotes_2.1.1     assertthat_0.2.1  digest_0.6.25     rprojroot_1.3-2  
[19] crayon_1.3.4      processx_3.4.2    callr_3.4.3       fs_1.4.1          ps_1.3.2          curl_4.3         
[25] testthat_2.3.2    memoise_1.1.0     glue_1.4.0        compiler_3.6.1    desc_1.2.0        backports_1.1.6  
[31] prettyunits_1.1.1

**Comment by joschif** [comment]
Thanks for the info. It seems like there is a mismatch between your R version (3.6.1) and the one `tibble` was build under (3.6.2). Installing a more recent version of R such as [3.6.3](https://cran.r-project.org/bin/macosx/R-3.6.3.pkg) might resolve the issue.

**Comment by fkrbry** [comment]
that did it, thank you!
