### ISSUE TITLE
How to display the color bar of correlation?

### ISSUE THREAD

**Issue by RUSTHONG** [quadbiolab/VoxHunt#6]
Hey, I think this package is an excellent work! 
But I had some problem when I plotted spatial similarity maps. I couldn't find any parameter explaining the color of correlation. I need a color bar to tell other people which color means low correlation and which color means high correlation, like this:

![微信图片_20210205110841](https://user-images.githubusercontent.com/32788067/106984461-9cebe400-67a2-11eb-8c64-1c3b46fce07e.png)

I'm looking forward to your response.
Thank you!

**Comment by joschif** [comment]
Hi @RUSTHONG,

In the `plot_map()` function in sagittal view, this can be controlled with the `show_legend` parameter. In the most recent version, this is per default set to `TRUE` and output something like this: 

![image](https://user-images.githubusercontent.com/25106724/107011698-4b3e5c00-6798-11eb-996c-7be77394aa54.png)

Unfortunately, I forgot to enable it in the coronal view so it only shows the structure colors. However the color scale should be the same as in sagittal view. I'll eneble it in a future version, thanks for the reminder.

Cheers,
Jonas

**Comment by RUSTHONG** [comment]
Oh, I know how to do it now. Thank you again!
