### ISSUE TITLE
Error using load_mousebrain_data

### ISSUE THREAD

**Issue by finjen** [quadbiolab/VoxHunt#8]
Hi, 
I'm having troubles loading the La Manno dataset using the function load_mousebrain_data.
The error I am receiving is the following:

load_mousebrain_data('~/dev_all.agg_new.loom')
Error in H5File.open(filename, mode, file_create_pl, file_access_pl) : 
  HDF5-API Errors:
    error #000: ../../../src/H5F.c in H5Fcreate(): line 444: unable to create file
        class: HDF5
        major: File accessibilty
        minor: Unable to open file

    error #001: ../../../src/H5Fint.c in H5F__create(): line 1364: unable to open file
        class: HDF5
        major: File accessibilty
        minor: Unable to open file

    error #002: ../../../src/H5Fint.c in H5F_open(): line 1557: unable to open file: time = Thu Feb 25 13:24:58 2021
, name = '/home/administrator/dev_all.agg_new.loom/dev_all.loom', tent_flags = 13
        class: HDF5
        major: File accessibilty
        minor: Unable to open file

    error #003: ../../../src/H5FD.c in H5FD_open(): line 734: open failed
        class: HDF5
        major: Virtual File Layer
        minor: Unable to initialize object

    error #004: ../../../src/H5FDsec2.c in H5FD_sec2_open(): line 346: unable to open file: name = '/home/administrator/dev_all.agg_new.loom/dev_all.loom', errno = 2

However, if I connect to the file using the LoomR connect function, there seems to be no problem. Can you please help me identifying the issue here? 

Best

**Comment by joschif** [comment]
I believe the problem is that you are pointing `load_mousebrain_data()` to the file `dev_all.agg_new.loom` instead of the directory it is in. The function needs both files (`dev_all.agg_new.loom`, `dev_all.loom`) to load the data so if you specify the directory they are in it should work. So if they are in your home directory: `load_mousebrain_data('~/')`

**Comment by finjen** [comment]
I see. I am pointing now to the directory that contains both files, however, I am facing now this error:

Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/home/administrator/R/x86_64-pc-linux-gnu-library/4.0/hdf5r/libs/hdf5r.so':
  libhdf5_hl.so.100: cannot open shared object file: No such file or directory

I have hdf5r installed and loaded. Not sure why this is happening.

**Comment by joschif** [comment]
There seems to be somethign wrong with your hdf5r, can you use it manually, e.g. by loading the loom file with it?
`loom_file <- hdf5r::H5File$new('~/dev_all.agg_new.loom')`

**Comment by finjen** [comment]
loom_file <- hdf5r::H5File$new("~/dev_all.agg.loom") works fine actually.

**Comment by joschif** [comment]
Interesting, and can you also obtain data from the file like so `genes <- loom_file[['row_attrs/Gene']][]`. The function `load_mousebrain_data()` actually does not do much more than these two steps, so I'm not quite sure why it would not work in this case.

**Comment by finjen** [comment]
Ah.. no actually when I try to do this, it gives me this error again:

genes <-loom_file[['row_attrs/Gene']][]
Error in x$exists(name) : HDF5-API Errors:
    error #000: ../../../src/H5L.c in H5Lexists(): line 815: unable to get link info
        class: HDF5
        major: Links
        minor: Can't get value

    error #001: ../../../src/H5L.c in H5L__exists(): line 3095: path doesn't exist
        class: HDF5
        major: Links
        minor: Object already exists

    error #002: ../../../src/H5Gtraverse.c in H5G_traverse(): line 851: internal path traversal failed
        class: HDF5
        major: Symbol table
        minor: Object not found

    error #003: ../../../src/H5Gtraverse.c in H5G__traverse_real(): line 741: component not found
        class: HDF5
        major: Symbol table
        minor: Object not found

So, something is going wrong with my hdf5r package I assume. That's weird. Do you have any idea what could be the source issue here? I never had any issues like that actually. 
Or is there maybe any other way of loading the mousebrain data for further functions to be able to detect it (instead of load_mousebrain_data)?

**Comment by joschif** [comment]
Just out of curiosity, can you list the contents of the file with `loom_file$ls(recursive=T)` and if that works, post the output? Otherwise maybe reinstalling hdf5r helps or if you can load the file with another pacakge like loomR we might also be able to get this to work with VoxHunt.

**Comment by finjen** [comment]
This seems to work, this is the output:

loom_file$ls(recursive = T)
 [1] name                link.type           obj_type            num_attrs           group.nlinks       
 [6] group.mounted       dataset.rank        dataset.dims        dataset.maxdims     dataset.type_class 
[11] dataset.space_class committed_type     
<0 rows> (or 0-length row.names)

Reinstalling the hdf5r package was successful, however load_mousebrain_data still results in the same error. And I had tried before (however, maybe not correctly) to load the data via loomR but using the following function I got the error below:

mb_map <- mousebrain_map(mydata, group_name = 'leiden_cluster', genes_use = regional_markers)
Error in mousebrain_map.default(object = Matrix::Matrix(expr_mat, sparse = T),  : 
  Data has not been loaded. Please run load_mousebrain_data() first.

**Comment by joschif** [comment]
Are you sure that the loom file is correct? To me the output suggests that the file is empty. For the expected file, the output shoudl be quite a large dataframe. E.g. for me the output of `loom_file$ls()`, with loom_file being `dev_all.agg.loom` looks like this
```
        name     link.type    obj_type num_attrs group.nlinks group.mounted dataset.rank dataset.dims
1      attrs H5L_TYPE_HARD   H5I_GROUP         0            4             0           NA         <NA>
2  col_attrs H5L_TYPE_HARD   H5I_GROUP         1          135             0           NA         <NA>
3 col_graphs H5L_TYPE_HARD   H5I_GROUP         0            0             0           NA         <NA>
4     layers H5L_TYPE_HARD   H5I_GROUP         0            2             0           NA         <NA>
5     matrix H5L_TYPE_HARD H5I_DATASET         0           NA            NA            2  942 x 31053
6  row_attrs H5L_TYPE_HARD   H5I_GROUP         1           12             0           NA         <NA>
7 row_graphs H5L_TYPE_HARD   H5I_GROUP         0            0             0           NA         <NA>
  dataset.maxdims dataset.type_class dataset.space_class committed_type
1            <NA>               <NA>                <NA>           <NA>
2            <NA>               <NA>                <NA>           <NA>
3            <NA>               <NA>                <NA>           <NA>
4            <NA>               <NA>                <NA>           <NA>
5     Inf x 31053          H5T_FLOAT          H5S_SIMPLE           <NA>
6            <NA>               <NA>                <NA>           <NA>
7            <NA>               <NA>                <NA>           <NA>
```

**Comment by finjen** [comment]
Sorry, indeed the file I had tried loading was damaged. I re-downloaded the loom files now again and tried 
loom_file <- hdf5r::H5File$new("~/Documents/Signatures/LaManno_Dev/dev_all.agg_new.loom")  which, again, worked without error and loom_file$ls() results in this as well: 
        name     link.type    obj_type num_attrs group.nlinks group.mounted dataset.rank dataset.dims
1      attrs H5L_TYPE_HARD   H5I_GROUP         0            4             0           NA         <NA>
2  col_attrs H5L_TYPE_HARD   H5I_GROUP         1          137             0           NA         <NA>
3 col_graphs H5L_TYPE_HARD   H5I_GROUP         0            0             0           NA         <NA>
4     layers H5L_TYPE_HARD   H5I_GROUP         0            2             0           NA         <NA>
5     matrix H5L_TYPE_HARD H5I_DATASET         0           NA            NA            2  798 x 31053
6  row_attrs H5L_TYPE_HARD   H5I_GROUP         1           12             0           NA         <NA>
7 row_graphs H5L_TYPE_HARD   H5I_GROUP         0            0             0           NA         <NA>
  dataset.maxdims dataset.type_class dataset.space_class committed_type
1            <NA>               <NA>                <NA>           <NA>
2            <NA>               <NA>                <NA>           <NA>
3            <NA>               <NA>                <NA>           <NA>
4            <NA>               <NA>                <NA>           <NA>
5     Inf x 31053          H5T_FLOAT          H5S_SIMPLE           <NA>
6            <NA>               <NA>                <NA>           <NA>
7            <NA>               <NA>                <NA>           <NA>

This works for both of the files. But with load_mousebrain_data, the output is still the same error.

**Comment by joschif** [comment]
I'm sorry you are experiencing these errors, and I still haven't figured out what the problem could be. Since the function is quite short, maybe you can try to run the function line by line manually and see whether that works. Here's the function definition:
https://github.com/quadbiolab/VoxHunt/blob/9ddcfcf7b0b6a1a1725f4f111fe41b0b6ef5553a/R/utils.R#L65

**Comment by finjen** [comment]
No worries. I am running the function through, and it is all fine until running the lines:
 MOUSEBRAIN_DATA <<- list(
    matrix = Matrix(agg_expression, sparse=T),
    meta = all_meta
  )
Out:
Error in Matrix(agg_expression, sparse = T) : 
  could not find function "Matrix"

I downloaded then the package Matrix and ran it again, then it went through without error. Also, the function load_mousebrain_data() works now without error. However, when I check agg_loom, the output is this:
Class: H5File
ID: Object invalid
Not sure this is ok?

Also, when I run 
mb_map <- mousebrain_map(mydata, group_name = 'leiden_cluster', genes_use = regional_markers)

I do get the error:
Error: Must subset rows with a valid subscript vector.
ℹ Logical subscripts must match the size of the indexed input.
x Input has size 49073 but subscript `!duplicated(x, fromLast = fromLast, ...)` has size 0.

Since it is the same than when running voxel_map, I guess loading the mouse brain data has worked now (?) but there is still something off with my data. How do you see it?

**Comment by joschif** [comment]
What's in `agg_loom` isn't really important, what counts is that `MOUSEBRAIN_DATA` contains an expression matrix and metadata. Can you maybe run `rlang::last_error()` again to get the backtrace?

**Comment by finjen** [comment]
I see. There is a spare matrix and metadata in MOUSEBRAIN_DATA. 

This is the output of rlang::last_error():
> rlang::last_error()
<error/vctrs_error_subscript_size>
Must subset rows with a valid subscript vector.
ℹ Logical subscripts must match the size of the indexed input.
x Input has size 49073 but subscript `!duplicated(x, fromLast = fromLast, ...)` has size 0.
Backtrace:
  1. voxhunt::voxel_map(...)
  2. voxhunt:::voxel_map.default(...)
  4. generics:::intersect.default(inter_genes, genes_use)
  5. base::intersect(x, y, ...)
  7. base::unique.data.frame(y[match(as.vector(x), y, 0L)])
  9. tibble:::`[.tbl_df`(...)
 10. tibble:::tbl_subset_row(xo, i = i, i_arg)
 11. tibble:::vectbl_as_row_index(i, x, i_arg)
 12. tibble:::vectbl_as_row_location(i, nr, i_arg, assign)
 15. vctrs::vec_as_location(i, n)
 17. vctrs:::stop_indicator_size(...)

And:

rlang::last_trace()
<error/vctrs_error_subscript_size>
Must subset rows with a valid subscript vector.
ℹ Logical subscripts must match the size of the indexed input.
x Input has size 49073 but subscript `!duplicated(x, fromLast = fromLast, ...)` has size 0.
Backtrace:
     █
  1. ├─voxhunt::voxel_map(...)
  2. └─voxhunt:::voxel_map.default(...)
  3.   ├─generics::intersect(inter_genes, genes_use)
  4.   └─generics:::intersect.default(inter_genes, genes_use)
  5.     └─base::intersect(x, y, ...)
  6.       ├─base::unique(y[match(as.vector(x), y, 0L)])
  7.       └─base::unique.data.frame(y[match(as.vector(x), y, 0L)])
  8.         ├─x[!duplicated(x, fromLast = fromLast, ...), , drop = FALSE]
  9.         └─tibble:::`[.tbl_df`(...)
 10.           └─tibble:::tbl_subset_row(xo, i = i, i_arg)
 11.             └─tibble:::vectbl_as_row_index(i, x, i_arg)
 12.               └─tibble:::vectbl_as_row_location(i, nr, i_arg, assign)
 13.                 ├─tibble:::subclass_row_index_errors(...)
 14.                 │ └─base::withCallingHandlers(...)
 15.                 └─vctrs::vec_as_location(i, n)
 16.                   └─(function () ...
 17.                     └─vctrs:::stop_indicator_size(...)

**Comment by Byronxy** [comment]
Hi, I got different errors. Could you please help me out?
```
load_mousebrain_data(dir = mousebrain_dir)
```
```
Error in H5File.open(filename, mode, file_create_pl, file_access_pl) : 
  HDF5-API Errors:
    error #000: ../../../src/H5F.c in H5Fopen(): line 579: unable to open file
        class: HDF5
        major: File accessibilty
        minor: Unable to open file

    error #001: ../../../src/H5Fint.c in H5F_open(): line 1208: unable to read superblock
        class: HDF5
        major: File accessibilty
        minor: Read failed

    error #002: ../../../src/H5Fsuper.c in H5F__super_read(): line 443: truncated file: eof = 2209382400, sblock->base_addr = 0, stored_eof = 10268831815
        class: HDF5
        major: File accessibilty
        minor: File has been truncated
```
```
sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.5 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] voxhunt_1.0.0

loaded via a namespace (and not attached):
  [1] nlme_3.1-151         matrixStats_0.57.0   bit64_4.0.5          RcppAnnoy_0.0.17     RColorBrewer_1.1-2   httr_1.4.2          
  [7] sctransform_0.3.1    tools_3.6.3          R6_2.5.0             irlba_2.3.3          rpart_4.1-15         KernSmooth_2.23-18  
 [13] uwot_0.1.9           mgcv_1.8-33          lazyeval_0.2.2       colorspace_2.0-0     tidyselect_1.1.0     gridExtra_2.3       
 [19] bit_4.0.4            compiler_3.6.3       hdf5r_1.3.3          plotly_4.9.2.1       Seurat_3.2.2         scales_1.1.1        
 [25] lmtest_0.9-38        spatstat.data_2.1-0  ggridges_0.5.2.9000  pbapply_1.4-3        spatstat_1.64-1      goftest_1.2-2       
 [31] stringr_1.4.0        digest_0.6.26        spatstat.utils_2.1-0 pkgconfig_2.0.3      htmltools_0.5.1.1    fastmap_1.0.1       
 [37] htmlwidgets_1.5.2    rlang_0.4.10         rstudioapi_0.13      shiny_1.5.0          farver_2.0.3         generics_0.1.0      
 [43] zoo_1.8-8            jsonlite_1.7.1       ica_1.0-2            dplyr_1.0.2          magrittr_2.0.1       patchwork_1.1.0     
 [49] Matrix_1.3-2         Rcpp_1.0.6           munsell_0.5.0        abind_1.4-5          reticulate_1.17      lifecycle_0.2.0     
 [55] stringi_1.5.3        MASS_7.3-53          Rtsne_0.15           plyr_1.8.6           grid_3.6.3           parallel_3.6.3      
 [61] listenv_0.8.0        promises_1.1.1       ggrepel_0.8.2        crayon_1.3.4         egg_0.4.5            miniUI_0.1.1.1      
 [67] deldir_0.2-3         lattice_0.20-41      cowplot_1.1.0        splines_3.6.3        tensor_1.5           pillar_1.4.7        
 [73] igraph_1.2.6         future.apply_1.6.0   reshape2_1.4.4       codetools_0.2-18     leiden_0.3.5         glue_1.4.2          
 [79] data.table_1.13.2    vctrs_0.3.5          png_0.1-7            httpuv_1.5.4         gtable_0.3.0         RANN_2.6.1          
 [85] purrr_0.3.4          polyclip_1.10-0      tidyr_1.1.2          future_1.19.1        ggplot2_3.3.3        xfun_0.18           
 [91] rsvd_1.0.3           mime_0.9             xtable_1.8-4         later_1.1.0.1        survival_3.2-7       viridisLite_0.3.0   
 [97] tibble_3.0.4         tinytex_0.26         cluster_2.1.0        globals_0.13.1       fitdistrplus_1.1-1   ellipsis_0.3.1      
[103] ROCR_1.0-11
